'use strict';

export const json = {
	"0": {
		"FIO": "Семеренський Олександр Володимирович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Инженер 1-й категории",
		"NameID": "ChemDep",
		"StatusID": "newCard",
		"IDUser": "1",
		"TitleID": "Пластиковая карта",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"1": {
		"FIO": "Горбунова-Рубан Свiтлана Олександрiвна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик",
		"NameID": "ChemDep",
		"StatusID": "newQR",
		"IDUser": "2",
		"TitleID": "QR-код",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"2": {
		"FIO": "Гарькавенко Володимир Володимирович",
		"Department": "Факультет компьютерных наук",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Инженер 2-й категории",
		"NameID": "CSDep",
		"StatusID": "newCard",
		"IDUser": "3",
		"TitleID": "Пластиковая карта",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"3": {
		"FIO": "Скоринiна-Погребна Ольга Володимирiвна",
		"Department": "Физико-технический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Инженер 2-й категории",
		"NameID": "PhTechDep",
		"StatusID": "newCard",
		"IDUser": "4",
		"TitleID": "Пластиковая карта",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	// "4": {
	// 	"FIO": "Суворова-Григорович Ганна Олександрiвна",
	// 	"Department": "Физический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер 1-й категории",
	// 	"NameID": "PhDep",
	// 	"StatusID": "newCard",
	// "IDUser": "5"
	// },
	// "5": {
	// 	"FIO": "Сотнiкова-Мелешкiна Жанна Владиславiвна",
	// 	"Department": "Биологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер",
	// 	"NameID": "BioDep",
	// 	"StatusID": "newCard",
	// "IDUser": "6"
	// },
	// "6": {
	// 	"FIO": "Бельорин-Еррера Олександра Михайлiвна",
	// 	"Department": "Биологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер",
	// 	"NameID": "BioDep",
	// 	"StatusID": "newCard",
	// "IDUser": "7"
	// },
	// "7": {
	// 	"FIO": "Корженевський Станiслав Володимирович",
	// 	"Department": "Физико-энергетический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "PhysEnDep",
	// 	"StatusID": "newCard",
	// "IDUser": "8"
	// },
	// "8": {
	// 	"FIO": "Добровольський Олександр В'ячеславович",
	// 	"Department": "Екологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "EcoDep",
	// 	"StatusID": "newCard",
	// "IDUser": "9"
	// },
	// "9": {
	// 	"FIO": "Пасiчник-Ледянко Валентина Миколаївна",
	// 	"Department": "Факультет психологии",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "PsyDep",
	// 	"StatusID": "newCard",
	// "IDUser": "10"
	// },
	// "10": {
	// 	"FIO": "Дем'яновська-Кононова Наталiя Михайлiвна",
	// 	"Department": "Филологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Преподаватель",
	// 	"NameID": "PhilolDep",
	// 	"StatusID": "newCard",
	// "IDUser": "11"
	// },
	// "11": {
	// 	"FIO": "Тесленко-Пономаренко Надiя Дмитрiвна",
	// 	"Department": "Экономический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Преподаватель",
	// 	"NameID": "EconomDep",
	// 	"StatusID": "newCard",
	// "IDUser": "12"
	// },
	// "12": {
	// 	"FIO": "Станиславський Олександр Олександрович",
	// 	"Department": "Социологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Секретарь",
	// 	"NameID": "SocDep",
	// 	"StatusID": "newCard",
	// "IDUser": "13"
	// }
	"13": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Социологический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "SocDep",
		"StatusID": "newQR",
		"IDUser": "14",
		"TitleID": "QR-код",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"14": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "ChemDep",
		"StatusID": "changeCard",
		"IDUser": "15",
		"TitleID": "Пластиковая карта",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"15": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Биологический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "BioDep",
		"StatusID": "changeQR",
		"IDUser": "16",
		"TitleID": "QR-код",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"16": {
		"FIO": "Ткаченко Володимир Володимирович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Декан",
		"NameID": "ChemDep",
		"StatusID": "changeQR",
		"IDUser": "17",
		"TitleID": "QR-код",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	"17": {
		"FIO": "Сидоренко Дмитро Юрiйович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Аспирант",
		"NameID": "ChemDep",
		"StatusID": "changeQR",
		"IDUser": "18",
		"TitleID": "QR-код",
		"NewFio": "",
		"NewPost": "",
		"NewDepart": ""
	},
	// "18": {
	// 	"FIO": "Рябчунова Анастасiя Валерiївна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Директор",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "19",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "19": {
	// 	"FIO": "Чуприна Юлiя Юрiївна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Секретарь",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "20",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "20": {
	// 	"FIO": "Шайтуро Ольга Павлiвна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Деловод",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "21",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "21": {
	// 	"FIO": "Хабарова Тетяна Володимирiвна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Механик",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "22",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "22": {
	// 	"FIO": "Оганесян Марина Оганесiвна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Студент",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "23",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "23": {
	// 	"FIO": "Мурза Олена Віталіївна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Старший слесарь",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "24",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "24": {
	// 	"FIO": "Зайцева Анастасiя Андрiївна",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Аспирант",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "25",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
	// "25": {
	// 	"FIO": "Передерiй Олександр Сергiйович",
	// 	"Department": "Химический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Старший преподаватель",
	// 	"NameID": "ChemDep",
	// 	"StatusID": "newCard",
	// 	"IDUser": "26",
	// 	"TitleID": "Пластиковая карта",
	// 	"NewFio": "",
	// 	"NewPost": "",
	// 	"NewDepart": ""
	// },
};
