'use strict';

export const json = {
	"0": {
		"FIO": "Семеренський Олександр Володимирович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"1": {
		"FIO": "Горбунова-Рубан Свiтлана Олександрiвна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"2": {
		"FIO": "Гарькавенко Володимир Володимирович",
		"Department": "Факультет компьютерных наук",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Инженер 2-й категории",
		"NameID": "CSDep",
		"StatusID": "newCard"
	},
	"3": {
		"FIO": "Скоринiна-Погребна Ольга Володимирiвна",
		"Department": "Физико-технический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Инженер 2-й категории",
		"NameID": "PhTechDep",
		"StatusID": "newCard"
	},
	// "4": {
	// 	"FIO": "Суворова-Григорович Ганна Олександрiвна",
	// 	"Department": "Физический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер 1-й категории",
	// 	"NameID": "PhDep",
	// 	"StatusID": "newCard"
	// },
	// "5": {
	// 	"FIO": "Сотнiкова-Мелешкiна Жанна Владиславiвна",
	// 	"Department": "Биологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер",
	// 	"NameID": "BioDep",
	// 	"StatusID": "newCard"
	// },
	// "6": {
	// 	"FIO": "Бельорин-Еррера Олександра Михайлiвна",
	// 	"Department": "Биологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Инженер",
	// 	"NameID": "BioDep",
	// 	"StatusID": "newCard"
	// },
	// "7": {
	// 	"FIO": "Корженевський Станiслав Володимирович",
	// 	"Department": "Физико-энергетический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "PhysEnDep",
	// 	"StatusID": "newCard"
	// },
	// "8": {
	// 	"FIO": "Добровольський Олександр В'ячеславович",
	// 	"Department": "Екологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "EcoDep",
	// 	"StatusID": "newCard"
	// },
	// "9": {
	// 	"FIO": "Пасiчник-Ледянко Валентина Миколаївна",
	// 	"Department": "Факультет психологии",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Ст. преподаватель",
	// 	"NameID": "PsyDep",
	// 	"StatusID": "newCard"
	// },
	// "10": {
	// 	"FIO": "Дем'яновська-Кононова Наталiя Михайлiвна",
	// 	"Department": "Филологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Преподаватель",
	// 	"NameID": "PhilolDep",
	// 	"StatusID": "newCard"
	// },
	// "11": {
	// 	"FIO": "Тесленко-Пономаренко Надiя Дмитрiвна",
	// 	"Department": "Экономический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Преподаватель",
	// 	"NameID": "EconomDep",
	// 	"StatusID": "newCard"
	// },
	// "12": {
	// 	"FIO": "Станиславський Олександр Олександрович",
	// 	"Department": "Социологический факультет",
	// 	"FieldGroup": "",
	// 	"Badge": "",
	// 	"CardName": "",
	// 	"CardID": "",
	// 	"CardValidTo": "",
	// 	"PIN": "",
	// 	"CardStatus": "1",
	// 	"Security": "0",
	// 	"Disalarm": "0",
	// 	"VIP": "0",
	// 	"DayNightCLM": "0",
	// 	"AntipassbackDisabled": "0",
	// 	"PhotoFile": "",
	// 	"EmployeeNumber": "",
	// 	"Post": "Секретарь",
	// 	"NameID": "SocDep",
	// 	"StatusID": "newCard"
	// }
	"13": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Социологический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "SocDep",
		"StatusID": "newQR"
	},
	"14": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "ChemDep",
		"StatusID": "changeCard"
	},
	"15": {
		"FIO": "Станиславський Олександр Олександрович",
		"Department": "Биологический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Секретарь",
		"NameID": "BioDep",
		"StatusID": "changeQR"
	},
	"16": {
		"FIO": "Ткаченко Володимир Володимирович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"17": {
		"FIO": "Сидоренко Дмитро Юрiйович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"18": {
		"FIO": "Рябчунова Анастасiя Валерiївна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"19": {
		"FIO": "Чуприна Юлiя Юрiївна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"20": {
		"FIO": "Шайтуро Ольга Павлiвна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"21": {
		"FIO": "Хабарова Тетяна Володимирiвна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"22": {
		"FIO": "Оганесян Марина Оганесiвна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"23": {
		"FIO": "Мурза Олена Віталіївна",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"24": {
		"FIO": "Мурза Олена Віталіївич",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
	"25": {
		"FIO": "Передерiй Олександр Сергiйович",
		"Department": "Химический факультет",
		"FieldGroup": "",
		"Badge": "",
		"CardName": "",
		"CardID": "",
		"CardValidTo": "",
		"PIN": "",
		"CardStatus": "1",
		"Security": "0",
		"Disalarm": "0",
		"VIP": "0",
		"DayNightCLM": "0",
		"AntipassbackDisabled": "0",
		"PhotoFile": "",
		"EmployeeNumber": "",
		"Post": "Старший механик управляющего",
		"NameID": "ChemDep",
		"StatusID": "newCard"
	},
};
